project 'Techno.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Techno' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for Techno

  target 'TechnoTests' do
    inherit! :search_paths
    pod 'TitleImageEdgeinsetsButton'
    # Pods for testing
  end

end
